// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqwiztzqzptcchwzakdk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhxd2l6dHpxenB0Y2Nod3pha2RrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTA5OTAsImV4cCI6MjA1ODA2Njk5MH0.z2yxoZ4YI3XmmTXc5uiUAvZ-TmO1gwKfjaQYUaO9-bM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);